### ISSUE TITLE
Nested Arrays

### ISSUE THREAD

**Issue by Illest-Maestro** [thisdavej/getJSON-google-sheets#4]
Is there a way to get the 1st value out of a nested array?

https://phantombuster.s3.amazonaws.com/12AdE4Q3Tac/ss3CH6otUeWB7fL14cmpXA/rsn-linkedin-profile-scraper.json

I use query as my filter. I’m able to get basic information such as first name {{general.firstname}}. However I’m not sure if I’m able to grab job titles with the current code. {{jobs.jobtitle}} won’t work because jobs is an array where they may have 4 or 8 job titles.

If I was able to get even the 1st or current job title that’d be great.

**Comment by thisdavej** [comment]
@Illest-Maestro thanks for pointing out this opportunity to improve the code.  I added support for nested arrays as described in your use case.  Please try it and let me know if you have issues.
