### ISSUE TITLE
Index of nested values

### ISSUE THREAD

**Issue by Illest-Maestro** [thisdavej/getJSON-google-sheets#7]
Hello,

Would love to be able to get certain indexes of nested values. The API I use uses the same values over and over again. Example:

"skills": [
      {
        "name": "Negotiation",
        "endorsements": "6"
      },
      {
        "name": "Sales",
        "endorsements": "4"
      },
      {
        "name": "Procurement",
        "endorsements": "3"
      }

Also I'm having trouble getting the filter to work when I haven't had trouble with it in the past. What am I missing?

![CleanShot 2020-01-10 at 17 34 15](https://user-images.githubusercontent.com/51370714/72193565-b8ce5c00-33cf-11ea-844f-cd7b8ff65448.png)

**Comment by thisdavej** [comment]
Retrieving values in nested arrays is supported feature.

In your example, you can get the value of `name` for the first `skill` using the following template syntax:

`{{skills[0].name}}`

Likewise, you can get the value for the name of the second skill using `{{skills[1].name}}`, etc.
